version: "3.9"

services:
  api:
    build: ./api
    ports: 
      - 3000:3000

  ui:
    image: nginx:1.23.2
    ports:
      - 4000:80
    volumes:
      - ./ui:/usr/share/nginx/html:ro
    depends_on:
      - api
